<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXvTfDmc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXvTfDmc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXvTfDmc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXvTfDmc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXvTfDmc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XvTfDmc',
    'container.build_id' => '7b67d518',
    'container.build_time' => 1589556742,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXvTfDmc');
